# Generated by Django 2.2.4 on 2019-08-13 03:53

import UploadDownload.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('file', models.FileField(default=None, max_length=1000, upload_to=UploadDownload.models.SingleFileUpload.loc_func)),
                ('md5sum', models.CharField(max_length=200)),
                ('md5sum_o', models.CharField(max_length=200)),
                ('file_url', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('username_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.SpcUser')),
            ],
            options={
                'unique_together': {('username', 'name', 'file_path')},
            },
        ),
    ]
