# Generated by Django 2.2.4 on 2019-08-13 03:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lock_tokens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token_str', models.CharField(default=lock_tokens.models.get_random_token, editable=False, max_length=32, unique=True)),
                ('locked_object_id', models.PositiveIntegerField()),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('locked_object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('locked_object_content_type', 'locked_object_id')},
            },
        ),
    ]
